M48
; DRILL file {KiCad (6.0.10)} date Wed Dec 28 18:35:16 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-28T18:35:16-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X52.903Y-51.644
X52.914Y-143.936
X192.196Y-51.644
X192.207Y-143.947
T0
M30
