M48
; DRILL file {KiCad (6.0.10)} date Sat Apr 22 01:27:30 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-22T01:27:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
%
G90
G05
T1
X80.208Y-52.268
X80.208Y-120.452
X216.972Y-52.268
X216.972Y-120.452
T0
M30
